<?xml version="1.0" encoding="UTF-8"?>
<jndi:namedResource xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:jdbc="http://xsd.tns.tibco.com/amf/models/sharedresource/jdbc" xmlns:jndi="http://xsd.tns.tibco.com/amf/models/sharedresource/jndi" xmlns:subject="http://xsd.tns.tibco.com/trinity/models/identity/subject" xmi:id="_kwkE0fYDEe2NsPpgjzXK9g" name="exceptionhandling_db.JDBCConnectionResource" type="jdbc:JdbcDataSource">
  <jndi:reference xmi:id="_kwxgMPYDEe2NsPpgjzXK9g" key="subjectJndiName" type="subject:SubjectConfiguration" value=""/>
  <jndi:configuration xsi:type="jdbc:JdbcDataSource" xmi:id="_kwxgMfYDEe2NsPpgjzXK9g" username="postgres" password="#!0M5mpqugp6aEyoyDekmoXSzuYzM+KIoC">
    <connectionConfig xsi:type="jdbc:NonXaConnection" xmi:id="_kwxgMvYDEe2NsPpgjzXK9g" jdbcDriver="org.postgresql.Driver" dbURL="jdbc:postgresql://localhost:5432/postgres"/>
  </jndi:configuration>
</jndi:namedResource>
